---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todolist.fullname" . }}
  labels:
    {{- include "todolist.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: 9000-tcp
  selector:
    {{- include "todolist.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
